export default function getAllProducts() {
  return [
    {
      id: 'Mens-Casual-001',
      slug: 'Mens-Casual',
      name:  "Mens Casual Premium Slim Fit T-Shirts ",
      category: 'Men\'s Shirts',
      price: 1_549_000,
      stock: 100,
      imageUrl: '/assets/images/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.png',
      description: "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    },
    {
      id: 'Mens-Cotton-001',
      slug: 'Mens-Cotton',
      name: "Mens Cotton Jacket",
      category: 'Men\'s Shirts',
      price: 1_549_000,
      stock: 100,
      imageUrl: '/assets/images/71li-ujtlUL._AC_UX679_.jpg',
      description: 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
    },
    {
      id: 'Mens-Casual-slim-002',
      slug: 'Mens-Casual-slim',
      name:  "Mens Casual Slim Fit",
      category: 'Men\'s Shirts',
      price: 1_909_000,
      stock: 5,
      imageUrl: '/assets/images/71YXzeOuslL._AC_UY879_.jpg',
      description: 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
    },
    {
      id: 'Jaket-Casual-001',
      slug: 'Jaket-Casual',
      name: 'Jaket Casual Polo',
      category: 'Men\'s Shirts',
      price: 1_909_000,
      stock: 0,
      imageUrl: '/assets/images/images.jpeg',
      description: "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    },
    {
      id: 'BIYLACLESEN Womens-001',
      slug: 'BIYLACLESEN-Womens',
      name: 'BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats',
      category: 'Women\'s Shirt',
      price: 1_549_000,
      stock: 100,
      imageUrl: '/assets/images/51Y5NI-I5jL._AC_UX679_.jpg',
      description: `Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates,`
    },
    {
      id: 'Hooded-Faux-001',
      slug: 'Hooded-Faux',
      name: "Hooded Faux Leather Moto Biker Jacket",
      category: 'Women\'s Shirt',
      price: 1_549_000,
      stock: 100,
      imageUrl: '/assets/images/zzzaaazazazzaazazza.jpg',
      description: "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON"
    },
    {
      id: 'Rain-Jacket-002',
      slug: 'Rain-Jacket',
      name: "Rain Jacket Women Windbreaker Striped",
      category: 'Women\'s Shirt',
      price: 1_909_000,
      stock: 5,
      imageUrl: `/assets/images/71HblAHs5xL._AC_UY879_-2.jpg`,
      description: "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
    },
    {
      id: 'Opna-Women003',
      slug: 'Opna-Women',
      name: "Opna Women's Short Sleeve Moisture",
      category: 'Women\'s Shirt',
      price: 1_909_000,
      stock: 0,
      imageUrl: `/assets/images/51eg55uWmdL._AC_UX679_.jpg`,
      description: `Comfortable, durable and timeless—it's number 1 for a reason. The classic '80s construction pairs a warm suede upper with neutral accents for style that tracks whether you're on court or on the go.`
    },
  ]
}